# Generated by Django 4.1.7 on 2023-08-12 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='FieldsTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_data', models.BinaryField(blank=True, null=True, verbose_name='Бинарные данные')),
                ('basket', models.BooleanField(blank=True, null=True, verbose_name='Положить товар в корзину')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Время')),
                ('date_time', models.DateTimeField(blank=True, null=True, verbose_name='Полная дата')),
                ('time_delta', models.DurationField(blank=True, null=True, verbose_name='Интервал времени')),
                ('small_int', models.SmallIntegerField(verbose_name='Маленькое целое')),
                ('pos_small', models.PositiveSmallIntegerField(verbose_name='Маленькое положительное')),
                ('int_num', models.IntegerField(verbose_name='Целое число')),
                ('pos_int', models.PositiveIntegerField(verbose_name='Положительное число')),
                ('big_int', models.BigIntegerField(verbose_name='Большое целое')),
                ('dicimal_num', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Десятичное число')),
                ('float_num', models.FloatField(verbose_name='Вещественное число')),
                ('name', models.CharField(max_length=50, verbose_name='Имя клиента')),
                ('description', models.TextField(verbose_name='Описание')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронный адрес')),
                ('file', models.FileField(upload_to='', verbose_name='Имя айла')),
                ('file_path', models.FilePathField(verbose_name='Путь до файла')),
                ('image_path', models.EmailField(max_length=100, verbose_name='Путь до картинки')),
                ('ip_adres', models.GenericIPAddressField(verbose_name='IP адрес')),
                ('slug_text', models.SlugField(verbose_name='Слаг')),
                ('url_text', models.SlugField(max_length=200, verbose_name='URL-адрес')),
                ('uuid_text', models.UUIDField(verbose_name='UUID-адрес')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='firstapp.company', verbose_name='Компания')),
            ],
        ),
    ]
