# Generated by Django 4.1.7 on 2023-09-05 18:53

from django.db import migrations, models
import django.db.models.deletion
import firstapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_alter_product_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(default=firstapp.models.number_default, unique=True, verbose_name='Номер')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('executed', models.BooleanField(default=False, verbose_name='Завершённый')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['number'],
            },
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['name'], 'verbose_name': 'Человек', 'verbose_name_plural': 'Люди'},
        ),
        migrations.AlterField(
            model_name='product',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='firstapp.company', verbose_name='Производитель'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='OrderPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.PositiveIntegerField(editable=False, verbose_name='Номер заказа')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='firstapp.product', verbose_name='Продукт')),
                ('quantity', models.IntegerField(default=1, verbose_name='Количество')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='firstapp.order', verbose_name='Заказ')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='firstapp.person', verbose_name='Заказчик'),
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(related_name='orders', through='firstapp.OrderPosition', to='firstapp.product', verbose_name='Продукт'),
        ),
    ]
